In [1]:
# Python code for dot product
def dot_product(x,y):
    return sum(i*j for i,j in zip(x,y,strict=True))

In [2]:
dot_product([3,2,6],[6,3,2])

36

In [9]:
import math
dot_product1 = 0
def norm_vector(v):
    dot_product1 = sum(i * i for i in v)
    return math.sqrt(dot_product1)

In [10]:
norm_vector([2,5,-3])

6.164414002968976

# Matrix

In [24]:
import numpy as np
def matrix_addition(x,y):
    xrows = len(x)
    xcols = len(x[0])
    yrows = len(y)
    ycols = len(y[0])
    if xrows != yrows or xcols != ycols:
        print("Sum is not defined as the matrices have different orders")
    else:
        z = x
        for i in range(xrows):
            for j in range(xcols):
                z[i][j] = z[i][j] + y[i][j]
    return z

In [25]:
x = np.array([[2,-1,5],[10,3,1],[-7,0,3]])
y = np.array([[3,2,9],[-7,-7,6],[1,2,-4]])
matrix_addition(x,y)

array([[ 5,  1, 14],
       [ 3, -4,  7],
       [-6,  2, -1]])

In [27]:
x = np.array([[2,-1,5],[10,3,1],[-7,0,3]])

In [28]:
2*x

array([[  4,  -2,  10],
       [ 20,   6,   2],
       [-14,   0,   6]])

In [30]:
# Scalar Multiplication
def scalar_multi(c,x):
    cx = x
    for i in range(len(x)):
        for j in range(len(x[0])):
            cx[i][j] = c*cx[i][j]
    return cx

In [32]:
scalar_multi(0.5,np.array([[-1,2],[2,-3]]))

array([[ 0,  1],
       [ 1, -1]])

In [34]:
# Subtraction of two matrices
def matrix_subtraction(x,y):
    xrows = len(x)
    xcols = len(x[0])
    yrows = len(y)
    ycols = len(y[0])
    if xrows != yrows or xcols != ycols:
        print("Sum is not defined as the matrices have different orders")
    else:
        z = x
        for i in range(xrows):
            for j in range(xcols):
                z[i][j] = z[i][j] - y[i][j]
    return z

In [35]:
a = np.array([[5,-9],[0,2],[0,4]])
b = np.array([[3,0],[6,-5],[2,5]])

In [36]:
matrix_subtraction(a,b)

array([[ 2, -9],
       [-6,  7],
       [-2, -1]])

In [56]:
# Multiplication of two matrices
def matrix_multiplication(x,y):
    xrows = len(x)
    xcols = len(x[0])
    yrows = len(y)
    ycols = len(y[0])
    if xcols != yrows:
        print("Sum is not defined as the matrices have different orders")
    else:
        z = [[0 for i in range(ycols)] for j in range(xrows)]
        #print(z)
        for i in range(xrows):
            for j in range(ycols):
                total = 0
                for ii in range(xcols):
                    total += x[i][ii] * y[ii][j]
                z[i][j] = total
    return z

In [57]:
a = np.array([[5,-9],[0,2]])
b = np.array([[3,0],[6,-5]])
matrix_multiplication(a,b)

[[-39, 45], [12, -10]]

In [49]:
# Transpose of a Matrix
def matrix_transpose(x):
    xrows = len(x)
    xcols = len(x[0])
    z = [[0 for i in range(xrows)] for j in range(xcols)]
    for i in range(xcols):
        for j in range(xrows):
            z[i][j] = x[j][i]
    return z

In [50]:
matrix_transpose(np.array([[5,-9],[0,2]]))

[[5, 0], [-9, 2]]